/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project_gui;

import javax.swing.*;
import java.io.*;
import java.util.*;

/**
 *
 * @author meone
 */
public class AddRegister extends javax.swing.JFrame {
    
    ArrayList <Registrasi> regis;
    ArrayList<Main_menu> menu;
    String [] agamaArray;
    String [] jkArray;
    /**
     * Creates new form AddRegister
     */
    public AddRegister() {
        initComponents();
        regis = new ArrayList<Registrasi>();
        menu = new ArrayList<Main_menu>();
        
        regisArrayList();
        
        agamaArray = new String[7];
        
        //isi array
        agamaArray[0] = "Islam";
        agamaArray[1] = "Kristen";
        agamaArray[2] = "Katolik";
        agamaArray[3] = "Budha";
        agamaArray[4] = "Hindu";
        agamaArray[5] = "Konghucu";
        agamaArray[6] = "Lainnya";
        
        //Set Combo Box
        Agama_r.setModel(new javax.swing.DefaultComboBoxModel<>(agamaArray));
        
        jkArray = new String[2];
        
        //Isi Array
        jkArray[0] = "Laki - Laki";
        jkArray[1] = "Perempuan";
        JK_r.setModel(new javax.swing.DefaultComboBoxModel<>(jkArray));
    }
    
    public void savetoFile(){
        
        try{
            
            FileOutputStream file = new FileOutputStream("regis.dat");
            ObjectOutputStream outputfile = new ObjectOutputStream(file);
            
            for (int i = 0; i < regis.size(); i++){
                outputfile.writeObject(regis.get(i));
            }
            
            outputfile.close();
            
            JOptionPane.showMessageDialog(null, "Successfully Register!!");
            
        }catch(IOException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
        try{
            
            FileOutputStream file2 = new FileOutputStream("menu.dat");
            ObjectOutputStream outputfile2 = new ObjectOutputStream(file2);
            
            for (int i = 0; i < menu.size(); i++){
                outputfile2.writeObject(menu.get(i));
            }
            
            outputfile2.close();
            
        }catch(IOException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
   
    }
    
    public void regisArrayList(){
        try{
            FileInputStream file = new FileInputStream("regis.dat");
            ObjectInputStream inputfile = new ObjectInputStream(file);
            
            boolean endoffile = false;
            
            while(!endoffile){
                try {
                    regis.add((Registrasi) inputfile.readObject());
                }catch (EOFException e){
                    endoffile = true;
                }catch (Exception f){
                    JOptionPane.showMessageDialog(null, f.getMessage());
                }
            }
            
            inputfile.close();
            
        }catch(IOException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
        try{
            FileInputStream file2 = new FileInputStream("menu.dat");
            ObjectInputStream inputfile2 = new ObjectInputStream(file2);
            
            boolean endoffile = false;
            
            while(!endoffile){
                try {
                    menu.add((Main_menu) inputfile2.readObject());
                }catch (EOFException e){
                    endoffile = true;
                }catch (Exception f){
                    JOptionPane.showMessageDialog(null, f.getMessage());
                }
            }
            
            inputfile2.close();
            
        }catch(IOException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
    }
    
    public boolean cekUsername(String Username){
        boolean cek = false;
        try{
            
            for (int i = 0; i < regis.size(); i++){
                if ( Username.equals(regis.get(i).getUserName()) ){
                    cek = true;
                    break;
                }
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        return cek;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        UserRegis = new javax.swing.JTextField();
        PassRegis = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        namaRegis = new javax.swing.JTextField();
        Nim_r = new javax.swing.JTextField();
        Email_r = new javax.swing.JTextField();
        TTL_r = new javax.swing.JTextField();
        Telepon_r = new javax.swing.JTextField();
        Agama_r = new javax.swing.JComboBox<>();
        Alamat_r = new javax.swing.JTextField();
        JK_r = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        SignInButton = new javax.swing.JPanel();
        SignIn = new javax.swing.JLabel();
        SignUpButton = new javax.swing.JPanel();
        signUp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Caladea", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Sign Up");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 40, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_gui/icons8-add-user-male-64.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Caladea", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Username ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Caladea", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Password");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 160, -1, -1));

        UserRegis.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(UserRegis, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 120, 320, -1));

        PassRegis.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(PassRegis, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 160, 320, -1));

        jLabel6.setFont(new java.awt.Font("Caladea", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Nama Lengkap ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 200, -1, -1));

        jLabel7.setFont(new java.awt.Font("Caladea", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Tempat, Tanggal Lahir");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 360, -1, -1));

        jLabel8.setFont(new java.awt.Font("Caladea", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Email");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 280, -1, -1));

        jLabel9.setFont(new java.awt.Font("Caladea", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("NIM ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 240, -1, -1));

        jLabel10.setFont(new java.awt.Font("Caladea", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Jenis Kelamin");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 400, -1, -1));

        jLabel11.setFont(new java.awt.Font("Caladea", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Agama");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 440, -1, -1));

        jLabel12.setFont(new java.awt.Font("Caladea", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Alamat ");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 480, -1, -1));

        jLabel13.setFont(new java.awt.Font("Caladea", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Telepon");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 320, -1, -1));

        namaRegis.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(namaRegis, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 200, 320, -1));

        Nim_r.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(Nim_r, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 240, 320, -1));

        Email_r.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(Email_r, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 280, 320, -1));

        TTL_r.setBackground(new java.awt.Color(255, 255, 255));
        TTL_r.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(TTL_r, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 360, 320, -1));

        Telepon_r.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(Telepon_r, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 320, 320, -1));

        Agama_r.setBackground(new java.awt.Color(255, 255, 255));
        Agama_r.setFont(new java.awt.Font("Caladea", 0, 15)); // NOI18N
        Agama_r.setForeground(new java.awt.Color(0, 0, 0));
        Agama_r.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Islam", "Kristen", "Katolik", "Budha", "Hindu", "Konghucu", "Lainnya" }));
        Agama_r.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agama_rActionPerformed(evt);
            }
        });
        jPanel1.add(Agama_r, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 440, 320, -1));

        Alamat_r.setBackground(new java.awt.Color(255, 255, 255));
        Alamat_r.setFont(new java.awt.Font("Caladea", 0, 15)); // NOI18N
        Alamat_r.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(Alamat_r, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 480, 320, -1));

        JK_r.setBackground(new java.awt.Color(255, 255, 255));
        JK_r.setFont(new java.awt.Font("Caladea", 0, 15)); // NOI18N
        JK_r.setForeground(new java.awt.Color(0, 0, 0));
        JK_r.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-Laki", "Perempuan" }));
        jPanel1.add(JK_r, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 400, 320, -1));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_gui/university_icon-icons.com_49967.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));

        jLabel14.setFont(new java.awt.Font("Caladea", 0, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Meone'S University");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 650));

        SignInButton.setBackground(new java.awt.Color(255, 255, 255));
        SignInButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SignInButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SignIn.setFont(new java.awt.Font("Caladea", 0, 15)); // NOI18N
        SignIn.setForeground(new java.awt.Color(0, 0, 0));
        SignIn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SignIn.setText("Sign In");
        SignIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignInMouseClicked(evt);
            }
        });
        SignInButton.add(SignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        jPanel1.add(SignInButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 530, 100, 30));

        SignUpButton.setBackground(new java.awt.Color(255, 255, 255));
        SignUpButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SignUpButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signUp.setFont(new java.awt.Font("Caladea", 0, 15)); // NOI18N
        signUp.setForeground(new java.awt.Color(0, 0, 0));
        signUp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signUp.setText("Sign Up");
        signUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signUpMouseClicked(evt);
            }
        });
        SignUpButton.add(signUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        jPanel1.add(SignUpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 530, 100, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Agama_rActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agama_rActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Agama_rActionPerformed

    private void signUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpMouseClicked
        // TODO add your handling code here:
        if (UserRegis.getText().isEmpty() || PassRegis.getText().isEmpty() ||
                namaRegis.getText().isEmpty() || Nim_r.getText().isEmpty() ||
                Email_r.getText().isEmpty() || TTL_r.getText().isEmpty() ||
                Telepon_r.getText().isEmpty() || Alamat_r.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please, Enter Your Username Or Password!!");
        }else{
            
            String Name = UserRegis.getText().trim();
            String Pass = PassRegis.getText().trim();
            String nama = namaRegis.getText().trim();
            String Nim = Nim_r.getText().trim();
            String email = Email_r.getText().trim();
            String TTL = TTL_r.getText().trim();
            String telepon = Telepon_r.getText().trim();
            String jenis_kelamin = jkArray[JK_r.getSelectedIndex()];
            String agama = agamaArray[Agama_r.getSelectedIndex()];
            String Alamat = Alamat_r.getText().trim();
            
            boolean cek = cekUsername(Name);
            
            if (cek){
                JOptionPane.showMessageDialog(null, Name + " Telah Digunakan, Silahkan Coba yang lain!");
            }else{
                Registrasi registrasi = new Registrasi(Name, Pass, nama, Nim, email, TTL,telepon, jenis_kelamin, agama, Alamat);
                regis.add(registrasi);            
            
                savetoFile();
            }           
            
        }
    }//GEN-LAST:event_signUpMouseClicked

    private void SignInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignInMouseClicked
        // TODO add your handling code here:
        AddLogin login = new AddLogin();
            
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SignInMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Agama_r;
    private javax.swing.JTextField Alamat_r;
    private javax.swing.JTextField Email_r;
    private javax.swing.JComboBox<String> JK_r;
    private javax.swing.JTextField Nim_r;
    private javax.swing.JPasswordField PassRegis;
    private javax.swing.JLabel SignIn;
    private javax.swing.JPanel SignInButton;
    private javax.swing.JPanel SignUpButton;
    private javax.swing.JTextField TTL_r;
    private javax.swing.JTextField Telepon_r;
    private javax.swing.JTextField UserRegis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JTextField namaRegis;
    private javax.swing.JLabel signUp;
    // End of variables declaration//GEN-END:variables
}
