/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project_gui;

import javax.swing.*;
import java.io.*;
import java.util.*;

/**
 *
 * @author meone
 */
public class AddLogin extends javax.swing.JFrame {
    
    ArrayList <Registrasi> regis;
    String [] cekName;
    String [] cekPass;
    /**
     * Creates new form AddLogin
     */
    public AddLogin() {
        initComponents();
        setLocationRelativeTo(null);
        regis = new ArrayList<Registrasi>();
        regisArrayList();
        
        cekName = new String[regis.size()];
        cekPass = new String[regis.size()];
        for (int i = 0; i < regis.size(); i++){
            cekName[i] = regis.get(i).getUserName();
            cekPass[i] = regis.get(i).getPassword();
        }
        
    }
    
    public void regisArrayList(){
        try{
            FileInputStream file = new FileInputStream("regis.dat");
            ObjectInputStream inputfile = new ObjectInputStream(file);
            
            boolean endoffile = false;
            
            while(!endoffile){
                try {
                    regis.add((Registrasi) inputfile.readObject());
                }catch (EOFException e){
                    endoffile = true;
                }catch (Exception f){
                    JOptionPane.showMessageDialog(null, f.getMessage());
                }
            }
            
            inputfile.close();
            
        }catch(IOException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    public int loginCheck(String Username, String Password){
        int index = 0;
        try{
            
            for (int i = 0; i < regis.size(); i++){
                if ( (Username.equals(cekName[i])) && Password.equals(cekPass[i]) ){
                    index = i;
                    break;
                }
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        return index;
    }
    
    public boolean boolloginCheck(String Username, String Password){
        boolean cek = false;
        try{
            
            for (int i = 0; i < regis.size(); i++){
                if ( (Username.equals(cekName[i])) && Password.equals(cekPass[i]) ){
                    cek = true;
                    break;
                }
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        return cek;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        UserLogin = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        PassLogin = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        SignUpButton = new javax.swing.JLabel();
        LoginButton = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sign In");
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1400, 650));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Caladea", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Sign In");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Caladea", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Username ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 230, 90, 30));

        UserLogin.setBackground(new java.awt.Color(255, 255, 255));
        UserLogin.setFont(new java.awt.Font("Caladea", 0, 18)); // NOI18N
        UserLogin.setForeground(new java.awt.Color(0, 0, 0));
        UserLogin.setOpaque(true);
        jPanel1.add(UserLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 230, 360, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_gui/frequently_asked_questions_icon_136575(1).png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 140, -1, -1));

        PassLogin.setBackground(new java.awt.Color(255, 255, 255));
        PassLogin.setFont(new java.awt.Font("Caladea", 0, 18)); // NOI18N
        PassLogin.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(PassLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 270, 360, -1));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_gui/university_icon-icons.com_49967.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));

        jLabel7.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Meone's University");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 650));

        jLabel5.setFont(new java.awt.Font("Caladea", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Password ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 270, 90, 30));

        jLabel2.setFont(new java.awt.Font("Caladea", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Need an Acoount ?");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 589, -1, 20));

        SignUpButton.setFont(new java.awt.Font("Caladea", 0, 15)); // NOI18N
        SignUpButton.setForeground(new java.awt.Color(0, 0, 0));
        SignUpButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SignUpButton.setText("Sign Up");
        SignUpButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignUpButtonMouseClicked(evt);
            }
        });
        jPanel1.add(SignUpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 589, 70, 20));

        LoginButton.setBackground(new java.awt.Color(255, 255, 255));
        LoginButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LoginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginButtonMouseClicked(evt);
            }
        });
        LoginButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Caladea", 0, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Login");
        LoginButton.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 80, 30));

        jPanel1.add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 310, 90, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_gui/ExitIcon.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SignUpButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpButtonMouseClicked
        // TODO add your handling code here:
        new AddRegister().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SignUpButtonMouseClicked

    private void LoginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtonMouseClicked
        // TODO add your handling code here:
        if (UserLogin.getText().isEmpty() || PassLogin.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Please, Enter Your UserName Or Password!!");

        } else{
            String Name = UserLogin.getText().trim();
            String Pass = PassLogin.getText().trim();

            int index = loginCheck(Name, Pass);
            boolean cek = boolloginCheck(Name, Pass);
            if ( cek ){
                MainMenu mainmenu = new MainMenu();
                 
                mainmenu.setVisible(true);
                mainmenu.namaDisplay(regis.get(index).getNama(), Name);
                mainmenu.Ambil(Name, Pass);
                                       
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(null, "UserName Or Password Wrong");
            }
        }
    }//GEN-LAST:event_LoginButtonMouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_jLabel10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LoginButton;
    private javax.swing.JPasswordField PassLogin;
    private javax.swing.JLabel SignUpButton;
    private javax.swing.JTextField UserLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
