/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project_gui;

/**
 *
 * @author meone
 */
public class Dashboard extends javax.swing.JFrame {
    String User;
    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public void namaDisplay(String Nama){
        Foto_name.setText(Nama);
    }
    
    public void profileDisplay(String Username, String Nama, String Nim, String TTL, String Email,
            String Jeniskelamin, String Agama, String Telepon, String Alamat){
        this.User = Username;
        ProfileName.setText(": " + Nama);
        ProfileNim.setText(": " + Nim);
        ProfileTTL.setText(": " + TTL);
        ProfileEmail.setText(": " + Email);
        ProfileTelepon.setText(": " + Telepon);
        ProfileJK.setText(": " + Jeniskelamin);
        ProfileAgama.setText(": " + Agama);
        ProfileAlamat.setText(": " + Alamat);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BackButton = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        ProfileName = new javax.swing.JLabel();
        ProfileNim = new javax.swing.JLabel();
        ProfileTTL = new javax.swing.JLabel();
        ProfileEmail = new javax.swing.JLabel();
        ProfileTelepon = new javax.swing.JLabel();
        ProfileJK = new javax.swing.JLabel();
        ProfileAgama = new javax.swing.JLabel();
        ProfileAlamat = new javax.swing.JLabel();
        Foto_name = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_gui/MainMenuIcon.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Caladea", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Meone's University");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, -1, -1));

        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_gui/ExitIcon.png"))); // NOI18N
        BackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackButtonMouseClicked(evt);
            }
        });
        jPanel2.add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 0, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 90));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Caladea", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Profile");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 30));

        jLabel5.setFont(new java.awt.Font("Caladea", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Nama");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jLabel7.setFont(new java.awt.Font("Caladea", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("NIM");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel8.setFont(new java.awt.Font("Caladea", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Tempat, Tanggal Lahir");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel9.setFont(new java.awt.Font("Caladea", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Email");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jLabel10.setFont(new java.awt.Font("Caladea", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Telepon");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jLabel11.setFont(new java.awt.Font("Caladea", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Jenis Kelamin");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jLabel12.setFont(new java.awt.Font("Caladea", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Agama");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        jLabel13.setFont(new java.awt.Font("Caladea", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Alamat");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 80, -1));

        ProfileName.setFont(new java.awt.Font("Caladea", 0, 24)); // NOI18N
        ProfileName.setForeground(new java.awt.Color(0, 0, 0));
        ProfileName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel3.add(ProfileName, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 600, 30));

        ProfileNim.setFont(new java.awt.Font("Caladea", 0, 24)); // NOI18N
        ProfileNim.setForeground(new java.awt.Color(0, 0, 0));
        ProfileNim.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel3.add(ProfileNim, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 600, 30));

        ProfileTTL.setFont(new java.awt.Font("Caladea", 0, 24)); // NOI18N
        ProfileTTL.setForeground(new java.awt.Color(0, 0, 0));
        ProfileTTL.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel3.add(ProfileTTL, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 600, 30));

        ProfileEmail.setFont(new java.awt.Font("Caladea", 0, 24)); // NOI18N
        ProfileEmail.setForeground(new java.awt.Color(0, 0, 0));
        ProfileEmail.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel3.add(ProfileEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 600, 30));

        ProfileTelepon.setFont(new java.awt.Font("Caladea", 0, 24)); // NOI18N
        ProfileTelepon.setForeground(new java.awt.Color(0, 0, 0));
        ProfileTelepon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel3.add(ProfileTelepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 600, 30));

        ProfileJK.setFont(new java.awt.Font("Caladea", 0, 24)); // NOI18N
        ProfileJK.setForeground(new java.awt.Color(0, 0, 0));
        ProfileJK.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel3.add(ProfileJK, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 600, 30));

        ProfileAgama.setFont(new java.awt.Font("Caladea", 0, 24)); // NOI18N
        ProfileAgama.setForeground(new java.awt.Color(0, 0, 0));
        ProfileAgama.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel3.add(ProfileAgama, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 600, 30));

        ProfileAlamat.setFont(new java.awt.Font("Caladea", 0, 24)); // NOI18N
        ProfileAlamat.setForeground(new java.awt.Color(0, 0, 0));
        ProfileAlamat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel3.add(ProfileAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, 600, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 1000, 500));

        Foto_name.setFont(new java.awt.Font("Caladea", 0, 18)); // NOI18N
        Foto_name.setForeground(new java.awt.Color(0, 0, 0));
        Foto_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Foto_name.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(Foto_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 570, 260, 40));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_gui/Profile.png"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 110, -1, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonMouseClicked
        // TODO add your handling code here:
        MainMenu mainmenu = new MainMenu();
                 
        mainmenu.setVisible(true);
        mainmenu.namaDisplay(ProfileName.getText(), User);
                                        
        this.dispose();
    }//GEN-LAST:event_BackButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackButton;
    private javax.swing.JLabel Foto_name;
    private javax.swing.JLabel ProfileAgama;
    private javax.swing.JLabel ProfileAlamat;
    private javax.swing.JLabel ProfileEmail;
    private javax.swing.JLabel ProfileJK;
    private javax.swing.JLabel ProfileName;
    private javax.swing.JLabel ProfileNim;
    private javax.swing.JLabel ProfileTTL;
    private javax.swing.JLabel ProfileTelepon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
