/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project_gui;

import javax.swing.*;
import java.io.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author meone
 */
public class MainMenu extends javax.swing.JFrame {
    
    ArrayList <Registrasi> regis;
    ArrayList<AmbilMatkul> list;
    String [] cekName;
    String [] cekPass;
    String Username, Password;
    
    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        
        setLocationRelativeTo(null);
        
        regis = new ArrayList<Registrasi>();
        list = new ArrayList<AmbilMatkul>();
        listArrayList();
        regisArrayList();
        
        cekName = new String[regis.size()];
        cekPass = new String[regis.size()];
        for (int i = 0; i < regis.size(); i++){
            cekName[i] = regis.get(i).getUserName();
            cekPass[i] = regis.get(i).getPassword();
        }
    }
    
    public void namaDisplay(String Nama, String Username){
        MMUsername1.setText(Username);
        MMUsername.setText(Nama);
    }
    
    public void Ambil(String Username, String Password){
        this.Username = Username;
        this.Password = Password;
    }
    
    public void listArrayList(){
        try{
            FileInputStream file2 = new FileInputStream("Matakuliah.dat");
            ObjectInputStream inputfile2 = new ObjectInputStream(file2);
            
            boolean endoffile = false;
            
            while(!endoffile){
                try {
                    list.add((AmbilMatkul) inputfile2.readObject());
                }catch (EOFException e){
                    endoffile = true;
                }catch (Exception f){
                    JOptionPane.showMessageDialog(null, f.getMessage());
                }
            }
            
            inputfile2.close();
            
        }catch(IOException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }       
        
    }
    
    public void regisArrayList(){
        try{
            FileInputStream file = new FileInputStream("regis.dat");
            ObjectInputStream inputfile = new ObjectInputStream(file);
            
            boolean endoffile = false;
            
            while(!endoffile){
                try {
                    regis.add((Registrasi) inputfile.readObject());
                }catch (EOFException e){
                    endoffile = true;
                }catch (Exception f){
                    JOptionPane.showMessageDialog(null, f.getMessage());
                }
            }
            
            inputfile.close();
            
        }catch(IOException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    public boolean loginCheck(String Username, String Password){
        boolean check = false;
        try{
            for (int i = 0; i < regis.size(); i++){
                
                if ( (MMUsername1.getText().equals(regis.get(i).getUserName())) ){
                    check = true;
                    break;
                }
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        return check;
    }
    
    public int AmbilIndex(String Username, String Password){
        int index =0;
        try{
            
            for (int i = 0; i < regis.size(); i++){
                if ( (MMUsername1.getText().equals(regis.get(i).getUserName())) ){
                    index = i;
                    break;
                }
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        return index;
    }
    
    public int AmbilIndextoTable(String Username){
        int index =0;
        try{
                        
            for (int i = 0; i < list.size(); i++){
                if (list.get(i).getUsername().equalsIgnoreCase(Username)){
                    index = i;
                    break;
                }
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        return index;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Menu2 = new javax.swing.JLabel();
        DashboardPanel = new javax.swing.JPanel();
        DashBoardButton = new javax.swing.JLabel();
        MataKuliah = new javax.swing.JPanel();
        MataKuliahButton = new javax.swing.JLabel();
        AmbilMK = new javax.swing.JPanel();
        AmbilMKButton = new javax.swing.JLabel();
        SPP = new javax.swing.JPanel();
        SppButton = new javax.swing.JLabel();
        ChangePassword = new javax.swing.JPanel();
        ChangeButton = new javax.swing.JLabel();
        LogOut = new javax.swing.JPanel();
        SignOutButton = new javax.swing.JLabel();
        Menu = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        MMUsername = new javax.swing.JLabel();
        MMUsername1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Caladea", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Meone's University");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_gui/MainMenuIcon.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 90));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_gui/3643769-building-home-house-main-menu-start_113416.png"))); // NOI18N
        Menu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu2MouseClicked(evt);
            }
        });
        jPanel3.add(Menu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        DashboardPanel.setBackground(new java.awt.Color(204, 204, 204));
        DashboardPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DashboardPanelMouseClicked(evt);
            }
        });
        DashboardPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DashBoardButton.setFont(new java.awt.Font("Caladea", 0, 15)); // NOI18N
        DashBoardButton.setForeground(new java.awt.Color(0, 0, 0));
        DashBoardButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DashBoardButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_gui/Dashboard.png"))); // NOI18N
        DashBoardButton.setText("Dashboard");
        DashBoardButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DashBoardButtonMouseClicked(evt);
            }
        });
        DashboardPanel.add(DashBoardButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 40));

        jPanel3.add(DashboardPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 160, 40));

        MataKuliah.setBackground(new java.awt.Color(204, 204, 204));
        MataKuliah.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MataKuliahButton.setFont(new java.awt.Font("Caladea", 0, 15)); // NOI18N
        MataKuliahButton.setForeground(new java.awt.Color(0, 0, 0));
        MataKuliahButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MataKuliahButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_gui/MataKuliah.png"))); // NOI18N
        MataKuliahButton.setText("Mata Kuliah");
        MataKuliahButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MataKuliahButtonMouseClicked(evt);
            }
        });
        MataKuliah.add(MataKuliahButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 160, 40));

        jPanel3.add(MataKuliah, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 160, 40));

        AmbilMK.setBackground(new java.awt.Color(204, 204, 204));
        AmbilMK.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AmbilMKButton.setFont(new java.awt.Font("Caladea", 0, 15)); // NOI18N
        AmbilMKButton.setForeground(new java.awt.Color(0, 0, 0));
        AmbilMKButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AmbilMKButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_gui/ambilMk_1.png"))); // NOI18N
        AmbilMKButton.setText("Ambil MK");
        AmbilMKButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AmbilMKButtonMouseClicked(evt);
            }
        });
        AmbilMK.add(AmbilMKButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 40));

        jPanel3.add(AmbilMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 160, 40));

        SPP.setBackground(new java.awt.Color(204, 204, 204));
        SPP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SppButton.setFont(new java.awt.Font("Caladea", 0, 15)); // NOI18N
        SppButton.setForeground(new java.awt.Color(0, 0, 0));
        SppButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SppButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_gui/SppIcon.png"))); // NOI18N
        SppButton.setText("SPP");
        SppButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SppButtonMouseClicked(evt);
            }
        });
        SPP.add(SppButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, 160, 40));

        jPanel3.add(SPP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 160, 40));

        ChangePassword.setBackground(new java.awt.Color(204, 204, 204));
        ChangePassword.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ChangeButton.setFont(new java.awt.Font("Caladea", 0, 15)); // NOI18N
        ChangeButton.setForeground(new java.awt.Color(0, 0, 0));
        ChangeButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ChangeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_gui/Icon Ceng Pass.png"))); // NOI18N
        ChangeButton.setText("Change Password");
        ChangeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChangeButtonMouseClicked(evt);
            }
        });
        ChangePassword.add(ChangeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 40));

        jPanel3.add(ChangePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 160, 40));

        LogOut.setBackground(new java.awt.Color(204, 204, 204));
        LogOut.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SignOutButton.setFont(new java.awt.Font("Caladea", 0, 15)); // NOI18N
        SignOutButton.setForeground(new java.awt.Color(0, 0, 0));
        SignOutButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SignOutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_gui/ExitIcon.png"))); // NOI18N
        SignOutButton.setText("Log Out");
        SignOutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignOutButtonMouseClicked(evt);
            }
        });
        LogOut.add(SignOutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 40));

        jPanel3.add(LogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 160, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 160, 560));

        Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_gui/3643769-building-home-house-main-menu-start_113416.png"))); // NOI18N
        Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuMouseClicked(evt);
            }
        });
        jPanel1.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_gui/Profile.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, -1, -1));

        MMUsername.setFont(new java.awt.Font("Caladea", 0, 15)); // NOI18N
        MMUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MMUsername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(MMUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 420, 170, 30));

        MMUsername1.setFont(new java.awt.Font("Caladea", 0, 15)); // NOI18N
        MMUsername1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(MMUsername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 380, 170, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    int x = 160;
    private void MenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuMouseClicked
        if (x == 0){
            jPanel3.show();
            jPanel3.setSize(x, 560);
            
            Thread th = new Thread(){
                @Override
                public void run(){
                    try{
                        for (int i = 0; i <= x; i++){
                            Thread.sleep(1);
                            jPanel3.setSize(x, 560);
                            
                        }
                    }catch (Exception e){
                        JOptionPane.showMessageDialog(null, e.getMessage());
                    }
                }
            };th.start();
            x = 160;
        }
    }//GEN-LAST:event_MenuMouseClicked

    private void Menu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu2MouseClicked
        
        if (x == 160){
            jPanel3.setSize(160,560);
            
            Thread th = new Thread() {
                @Override
                public void run(){
                    try {
                        for (int i = 160; i >=0; i--){
                            Thread.sleep(1);
                            jPanel3.setSize(i, 560);
                        }
                    }catch (Exception e){
                        JOptionPane.showMessageDialog(null, e.getMessage());
                        
                    }
                }
            };th.start();
            x=0;   
        }
    }//GEN-LAST:event_Menu2MouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void DashboardPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardPanelMouseClicked
        // TODO add your handling code here:]
        boolean cek = loginCheck(Username,Password);
        int index = AmbilIndex(Username, Password);
        
        if (cek){
            Dashboard DB = new Dashboard();
            
            DB.setVisible(true);
            DB.namaDisplay(regis.get(index).getNama());
            
            String Username = regis.get(index).getUserName();
            String Nama = regis.get(index).getNama();
            String Nim = regis.get(index).getNim();
            String TTL = regis.get(index).getTTL();
            String Email = regis.get(index).getEmail();
            String Telepon = regis.get(index).getTelepon();
            String JK = regis.get(index).getJK();
            String Agama = regis.get(index).getAgama();
            String Alamat = regis.get(index).getAlamat();
            
            DB.profileDisplay(Username, Nama, Nim, TTL, Email, JK, Agama, Telepon, Alamat);
            
            this.dispose();
        }
    }//GEN-LAST:event_DashboardPanelMouseClicked

    private void SignOutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignOutButtonMouseClicked
        // TODO add your handling code here:
        new AddLogin().setVisible(true);
        new MainMenu().setVisible(false);
        this.dispose();
    }//GEN-LAST:event_SignOutButtonMouseClicked

    private void ChangeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangeButtonMouseClicked
        // TODO add your handling code here:
        boolean cek = loginCheck(Username,Password);
        int index = AmbilIndex(Username, Password);
        
        if (cek){
            ChangePass tukar = new ChangePass();
            tukar.setVisible(true);
            
            String Username = regis.get(index).getUserName();
            String Password = regis.get(index).getNama();
            
            tukar.Ambil(regis.get(index).getUserName(), regis.get(index).getNama());
                        
            this.dispose();
        }
    }//GEN-LAST:event_ChangeButtonMouseClicked

    private void SppButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SppButtonMouseClicked
        // TODO add your handling code here:
        boolean cek = loginCheck(Username,Password);
        int index = AmbilIndex(Username, Password);
        
        if (cek){
            SPPForm spp = new SPPForm();
            
            spp.setVisible(true);
            
            String Username = regis.get(index).getUserName();
            String Nama = regis.get(index).getNama();
            String Nim = regis.get(index).getNim();
            
            spp.sppDisplay(Username, Nama, Nim);
            this.dispose();
        }
    }//GEN-LAST:event_SppButtonMouseClicked

    private void AmbilMKButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AmbilMKButtonMouseClicked
        // TODO add your handling code here:
        boolean cek = loginCheck(Username,Password);
        int index = AmbilIndex(Username, Password);
        
        if (cek){
            AmbilMk mk = new AmbilMk();
            
            mk.setVisible(true);
            
            String Username = regis.get(index).getUserName();
            String Nama = regis.get(index).getNama();
            String Nim = regis.get(index).getNim();
            
            mk.Ambil(Username, Nama);
            this.dispose();
        }
    }//GEN-LAST:event_AmbilMKButtonMouseClicked

    private void MataKuliahButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MataKuliahButtonMouseClicked
        // TODO add your handling code here:
        boolean cek = loginCheck(Username,Password);
        int index = AmbilIndex(Username, Password);
        int tableIndex = AmbilIndextoTable(regis.get(index).getUserName());
        int getmk = tableIndex + 5;
        if (cek){
            try{
                AddMataKuliah matkul = new AddMataKuliah();
                        
                while (tableIndex < getmk){
                    String Kode = list.get(tableIndex).getKode();
                    String Matakuliah = list.get(tableIndex).getMatakuliah();
                    String SKS = list.get(tableIndex).getSKS();
                    String Kelas = list.get(tableIndex).getKelas();
                    String Dosen = list.get(tableIndex).getDosen();
                    String Jadwal = list.get(tableIndex).getJadwal();
                    String Ruang = list.get(tableIndex).getRuang();
                
                    matkul.tableMode(Kode, Matakuliah, SKS, Kelas, Dosen, Jadwal, Ruang);
                    
                    tableIndex +=1;
                
                }
            
                matkul.setVisible(true);
            
                String Username = regis.get(index).getUserName();
                String Nama = regis.get(index).getNama();
            
                matkul.AmbilToDisplay(Username, Nama);
            
            this.dispose();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
            
        }
    }//GEN-LAST:event_MataKuliahButtonMouseClicked

    private void DashBoardButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashBoardButtonMouseClicked
        // TODO add your handling code here:
        boolean cek = loginCheck(Username,Password);
        int index = AmbilIndex(Username, Password);
        
        if (cek){
            Dashboard DB = new Dashboard();
            
            DB.setVisible(true);
            DB.namaDisplay(regis.get(index).getNama());
            
            String Username = regis.get(index).getUserName();
            String Nama = regis.get(index).getNama();
            String Nim = regis.get(index).getNim();
            String TTL = regis.get(index).getTTL();
            String Email = regis.get(index).getEmail();
            String Telepon = regis.get(index).getTelepon();
            String JK = regis.get(index).getJK();
            String Agama = regis.get(index).getAgama();
            String Alamat = regis.get(index).getAlamat();
            
            DB.profileDisplay(Username, Nama, Nim, TTL, Email, JK, Agama, Telepon, Alamat);
            
            this.dispose();
        }
    }//GEN-LAST:event_DashBoardButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AmbilMK;
    private javax.swing.JLabel AmbilMKButton;
    private javax.swing.JLabel ChangeButton;
    private javax.swing.JPanel ChangePassword;
    private javax.swing.JLabel DashBoardButton;
    private javax.swing.JPanel DashboardPanel;
    private javax.swing.JPanel LogOut;
    private javax.swing.JLabel MMUsername;
    private javax.swing.JLabel MMUsername1;
    private javax.swing.JPanel MataKuliah;
    private javax.swing.JLabel MataKuliahButton;
    private javax.swing.JLabel Menu;
    private javax.swing.JLabel Menu2;
    private javax.swing.JPanel SPP;
    private javax.swing.JLabel SignOutButton;
    private javax.swing.JLabel SppButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
